# Configuraci贸n Jekyll para documentaci贸n
title: Tintum.app
description: Documentaci贸n del proyecto web de Tintum.app
baseurl: ""
url: "https://tintum.app"

# Configuraci贸n de Liquid
liquid:
  error_mode: strict
  strict_filters: true
  strict_variables: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Excluir archivos
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

